# Pandas (cont.)

# 1. 인덱싱

## 1) 특정 행만 조회 - selection연산자
- df[시작인덱스:끝인덱스+1]
- 연속되는 일정구간의 행을 조회할 때

In [1]:
import pandas as pd

In [2]:
lemonade=pd.read_csv('lemonade2.csv')

# 0~4행 indexing

lemonade[0:5]

In [3]:
lemonade[0:5]

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97           70      90.0   0.25   164    41.00
1  7/2/2016     Park     98           72      90.0   0.25   165    41.25
2  7/3/2016     Park    110           71     104.0   0.25   187    46.75
3  7/4/2016    Beach    134           76      98.0   0.25   233    58.25
4  7/5/2016    Beach    159           78     135.0   0.25   277    69.25

#연속되지 않는 1,3,5행을 indexing하고 싶다면?
lemonade[1,3,5]  # 안됨!

#한행만 indexing하고 싶다면?
lemonade[1]  # 역시안됨!

### [참고] 1,3,5 행의 조회나 한행만 조회하는 것은 
- df.loc, df.iloc로 해야함. 이후 다룰 예정

## 2) 특정 열만 조회
- df[['col1','col2',..]] (이중 괄호임에 주의!)
- 연속/불연속, 한개/여러개 상관없이 가능

# 두 열만 조회: Dataframe으로 출력 
lemonade[['Date', 'Location']]

In [6]:
lemonade[['Date', 'Location']]

         Date Location
0    7/1/2016     Park
1    7/2/2016     Park
2    7/3/2016     Park
3    7/4/2016    Beach
4    7/5/2016    Beach
5    7/6/2016    Beach
6    7/6/2016    Beach
7    7/7/2016    Beach
8         NaN    Beach
9    7/9/2016    Beach
10  7/10/2016    Beach
11  7/11/2016    Beach
12  7/12/2016    Beach
13  7/13/2016    Beach
14  7/14/2016    Beach
15  7/15/2016    Beach
16  7/16/2016    Beach
17  7/17/2016    Beach
18  7/18/2016     Park
19  7/19/2016     Park
20  7/20/2016     Park
21  7/21/2016     Park
22  7/22/2016     Park
23  7/23/2016     Park
24  7/24/2016     Park
25  7/25/2016     Park
26  7/26/2016     Park
27  7/27/2016     Park
28  7/28/2016     Park
29  7/29/2016     Park
30  7/30/2016    Beach
31  7/31/2016    Beach

# 한 열만 조회: Dataframe으로 출력  
lemonade[['Date']] #이중괄호 - DataFrame으로 출력

In [7]:
lemonade[['Date']]

         Date
0    7/1/2016
1    7/2/2016
2    7/3/2016
3    7/4/2016
4    7/5/2016
5    7/6/2016
6    7/6/2016
7    7/7/2016
8         NaN
9    7/9/2016
10  7/10/2016
11  7/11/2016
12  7/12/2016
13  7/13/2016
14  7/14/2016
15  7/15/2016
16  7/16/2016
17  7/17/2016
18  7/18/2016
19  7/19/2016
20  7/20/2016
21  7/21/2016
22  7/22/2016
23  7/23/2016
24  7/24/2016
25  7/25/2016
26  7/26/2016
27  7/27/2016
28  7/28/2016
29  7/29/2016
30  7/30/2016
31  7/31/2016

In [8]:
# 이렇게 하면 어떻게 될까?  Series로 출력
lemonade['Date']  #단일괄호 - Series로 출력

0      7/1/2016
1      7/2/2016
2      7/3/2016
3      7/4/2016
4      7/5/2016
5      7/6/2016
6      7/6/2016
7      7/7/2016
8           NaN
9      7/9/2016
10    7/10/2016
11    7/11/2016
12    7/12/2016
13    7/13/2016
14    7/14/2016
15    7/15/2016
16    7/16/2016
17    7/17/2016
18    7/18/2016
19    7/19/2016
20    7/20/2016
21    7/21/2016
22    7/22/2016
23    7/23/2016
24    7/24/2016
25    7/25/2016
26    7/26/2016
27    7/27/2016
28    7/28/2016
29    7/29/2016
30    7/30/2016
31    7/31/2016
Name: Date, dtype: object

## 3) loc - 원하는 행, 원하는 열 조회
* **df.loc[[원하는 행index], [원하는 열이름]]**

lemonade.loc[[1,3,5], ['Date','Location']]

In [9]:
lemonade.loc[[1,3,5], ['Date','Location']]

       Date Location
1  7/2/2016     Park
3  7/4/2016    Beach
5  7/6/2016    Beach

lemonade.loc[[0], ['Date','Location']]

In [10]:
lemonade.loc[[0], ['Date','Location']]

       Date Location
0  7/1/2016     Park

- 행만지정 (열은 모두 추출): df.loc[[원하는 행index]]
- 열만지정 (행은 모두 추출): df.loc[ : , [원하는 열이름]]

#index 0행 하나만 (모든열에 대해) 추출
lemonade.loc[[0]]

In [12]:
lemonade.loc[[0]]

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97           70      90.0   0.25   164     41.0

#이렇게 하면 어떻게 될까?
lemonade.loc[0]  #단일괄호 - Series로 출력

In [13]:
lemonade.loc[0]

Date           7/1/2016
Location           Park
Lemon                97
Temperature          70
Leaflets           90.0
Price              0.25
Sold                164
Revenue            41.0
Name: 0, dtype: object

#index 1,3,5행을 (모든열에 대해) 추출하고 싶다면
lemonade.loc[[1,3,5]]

In [14]:
lemonade.loc[[1,3,5]]

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
1  7/2/2016     Park     98           72      90.0   0.25   165    41.25
3  7/4/2016    Beach    134           76      98.0   0.25   233    58.25
5  7/6/2016    Beach    103           82      90.0   0.25   172    43.00

#column 'Date','Location'을 (모든행에 대해) 추출하고 싶다면?
lemonade.loc[:, ['Date','Location']]

In [15]:
lemonade.loc[:, ['Date','Location']]

         Date Location
0    7/1/2016     Park
1    7/2/2016     Park
2    7/3/2016     Park
3    7/4/2016    Beach
4    7/5/2016    Beach
5    7/6/2016    Beach
6    7/6/2016    Beach
7    7/7/2016    Beach
8         NaN    Beach
9    7/9/2016    Beach
10  7/10/2016    Beach
11  7/11/2016    Beach
12  7/12/2016    Beach
13  7/13/2016    Beach
14  7/14/2016    Beach
15  7/15/2016    Beach
16  7/16/2016    Beach
17  7/17/2016    Beach
18  7/18/2016     Park
19  7/19/2016     Park
20  7/20/2016     Park
21  7/21/2016     Park
22  7/22/2016     Park
23  7/23/2016     Park
24  7/24/2016     Park
25  7/25/2016     Park
26  7/26/2016     Park
27  7/27/2016     Park
28  7/28/2016     Park
29  7/29/2016     Park
30  7/30/2016    Beach
31  7/31/2016    Beach

#참고 - 또다른 방법
lemonade[['Date','Location']]

In [16]:
lemonade[['Date','Location']]

         Date Location
0    7/1/2016     Park
1    7/2/2016     Park
2    7/3/2016     Park
3    7/4/2016    Beach
4    7/5/2016    Beach
5    7/6/2016    Beach
6    7/6/2016    Beach
7    7/7/2016    Beach
8         NaN    Beach
9    7/9/2016    Beach
10  7/10/2016    Beach
11  7/11/2016    Beach
12  7/12/2016    Beach
13  7/13/2016    Beach
14  7/14/2016    Beach
15  7/15/2016    Beach
16  7/16/2016    Beach
17  7/17/2016    Beach
18  7/18/2016     Park
19  7/19/2016     Park
20  7/20/2016     Park
21  7/21/2016     Park
22  7/22/2016     Park
23  7/23/2016     Park
24  7/24/2016     Park
25  7/25/2016     Park
26  7/26/2016     Park
27  7/27/2016     Park
28  7/28/2016     Park
29  7/29/2016     Park
30  7/30/2016    Beach
31  7/31/2016    Beach

- loc로 연속된 행 추출시
    - 0-m행, 특정열 추출
    - **df.loc[0:m, [원하는 열이름]]**         
        - 주의: selection연산자(:)가 있는 부분은 대괄호 [] 하지 않음

#행-index 1~3, 열-["Date", "Location"]
lemonade.loc[1:3,["Date", "Location"]]

In [17]:
lemonade.loc[1:3,["Date", "Location"]]

       Date Location
1  7/2/2016     Park
2  7/3/2016     Park
3  7/4/2016    Beach

#행-index 1~3, 열-전부
lemonade.loc[1:3]

In [18]:
lemonade.loc[1:3]

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
1  7/2/2016     Park     98           72      90.0   0.25   165    41.25
2  7/3/2016     Park    110           71     104.0   0.25   187    46.75
3  7/4/2016    Beach    134           76      98.0   0.25   233    58.25

#### [정리1]
- loc는 DataFrame의 함수가 아니라 속성임
- df.loc[] (df.loc()가 아니였음)
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

#### [정리2]
- 원하는 열은 반드시 열이름으로 추출해야 함
- 원하는 열에 맵핑되는 숫자(index)로 추출할 수 없음

In [19]:
lemonade.loc[[1,3,5], ['Date','Location']]

       Date Location
1  7/2/2016     Park
3  7/4/2016    Beach
5  7/6/2016    Beach

# 위 코드를 이렇게 바꾸면? (column명도 숫자(index)로 변경)
lemonade.loc[[1,3,5],[0,1]]    #안됨

## 4) iloc - 원하는 행과 열을 index로 조회
* **df.iloc[[원하는 행index], [원하는 열index]]**
- 행만지정 (열은 모두 추출): df.iloc[[원하는 행index]]
- 열만지정 (행은 모두 추출): df.iloc[:,[원하는 열index]]

# 행:0,1,2, 열:1,2를 원할 때
lemonade.iloc[[0,1,2], [1,2]]

In [21]:
lemonade.iloc[[0,1,2], [1,2]]

  Location  Lemon
0     Park     97
1     Park     98
2     Park    110

# 행:0,1,2 만 추출 (열은 모두 추출)
lemonade.iloc[[0,1,2]]

In [22]:
lemonade.iloc[[0,1,2]]

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97           70      90.0   0.25   164    41.00
1  7/2/2016     Park     98           72      90.0   0.25   165    41.25
2  7/3/2016     Park    110           71     104.0   0.25   187    46.75

# 열: 1,3,5만 추출 (행은 모두 추출) 
lemonade.iloc[:, [1,3,5]]

In [24]:
lemonade.iloc[:, [1,3,5]]

   Location  Temperature  Price
0      Park           70   0.25
1      Park           72   0.25
2      Park           71   0.25
3     Beach           76   0.25
4     Beach           78   0.25
5     Beach           82   0.25
6     Beach           82   0.25
7     Beach           81   0.25
8     Beach           82   0.25
9     Beach           80   0.25
10    Beach           82   0.25
11    Beach           83   0.25
12    Beach           84   0.25
13    Beach           77   0.25
14    Beach           78   0.25
15    Beach           75   0.50
16    Beach           74   0.50
17    Beach           77   0.50
18     Park           81   0.50
19     Park           78   0.50
20     Park           70   0.50
21     Park           77   0.50
22     Park           80   0.50
23     Park           81   0.50
24     Park           82   0.50
25     Park           84   0.50
26     Park           83   0.35
27     Park           80   0.35
28     Park           82   0.35
29     Park           81   0.35
30    Beach           82   0.35
31    Beach           82   0.35

- iloc으로 연속된 구간 추출시
     - 0-m행, 0-n열 추출
    - **df.iloc[0:m+1, 0:n+1]** 
        - 주의1: "끝나는 index+1" (loc와 비교)
        - 주의2: selection연산자(:)가 있는 부분은 대괄호 [] 하지 않음

lemonade.iloc[0:3, 0:2]

In [26]:
lemonade.iloc[0:3, 0:2]

       Date Location
0  7/1/2016     Park
1  7/2/2016     Park
2  7/3/2016     Park

In [28]:
# 그럼 아래 코드로 첫 2열(0,1)을 추출할 수 있을까?
lemonade.iloc[0:2]   #안됨 (행으로 간주)

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97           70      90.0   0.25   164    41.00
1  7/2/2016     Park     98           72      90.0   0.25   165    41.25

# 열로 간주할 수 있도록 처리하면 됨
lemonade.iloc[:, 0:2]   #ok

In [29]:
lemonade.iloc[:, 0:2]

         Date Location
0    7/1/2016     Park
1    7/2/2016     Park
2    7/3/2016     Park
3    7/4/2016    Beach
4    7/5/2016    Beach
5    7/6/2016    Beach
6    7/6/2016    Beach
7    7/7/2016    Beach
8         NaN    Beach
9    7/9/2016    Beach
10  7/10/2016    Beach
11  7/11/2016    Beach
12  7/12/2016    Beach
13  7/13/2016    Beach
14  7/14/2016    Beach
15  7/15/2016    Beach
16  7/16/2016    Beach
17  7/17/2016    Beach
18  7/18/2016     Park
19  7/19/2016     Park
20  7/20/2016     Park
21  7/21/2016     Park
22  7/22/2016     Park
23  7/23/2016     Park
24  7/24/2016     Park
25  7/25/2016     Park
26  7/26/2016     Park
27  7/27/2016     Park
28  7/28/2016     Park
29  7/29/2016     Park
30  7/30/2016    Beach
31  7/31/2016    Beach

## 5) 조건 인덱싱 (Boolean Indexing과 유사)

#조건에 해당되는 행만 출력
lemonade['Location'] == 'Beach'

In [30]:
lemonade['Location'] == 'Beach'

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30     True
31     True
Name: Location, dtype: bool

* **만약 조건을 만족하는 lemonade의 행을 모두 출력하게 하려면?**
* **lemonade[조건]**

lemonade[lemonade['Location'] == 'Beach']

In [31]:
lemonade[lemonade['Location'] == 'Beach']

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
3    7/4/2016    Beach    134           76      98.0   0.25   233    58.25
4    7/5/2016    Beach    159           78     135.0   0.25   277    69.25
5    7/6/2016    Beach    103           82      90.0   0.25   172    43.00
6    7/6/2016    Beach    103           82      90.0   0.25   172    43.00
7    7/7/2016    Beach    143           81     135.0   0.25   244    61.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
9    7/9/2016    Beach    134           80     126.0   0.25   229    57.25
10  7/10/2016    Beach    140           82     131.0   0.25   238    59.50
11  7/11/2016    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2016    Beach    130           84      99.0   0.25   225    56.25
13  7/13/2016    Beach    109           77      99.0   0.25   184    46.00
14  7/14/2016    Beach    122           78     113.0   0.25   207    51.75
15  7/15/2016    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2016    Beach     81           74      90.0   0.50   131    65.50
17  7/17/2016    Beach    115           77     126.0   0.50   191    95.50
30  7/30/2016    Beach     88           82      81.0   0.35   145    50.75
31  7/31/2016    Beach     76           82      68.0   0.35   123    43.05

# 조건이 하나일 때, 모든 열 출력
lemonade.loc[lemonade['Revenue']>45]

In [32]:
lemonade.loc[lemonade['Revenue']>45]

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
2    7/3/2016     Park    110           71     104.0   0.25   187    46.75
3    7/4/2016    Beach    134           76      98.0   0.25   233    58.25
4    7/5/2016    Beach    159           78     135.0   0.25   277    69.25
7    7/7/2016    Beach    143           81     135.0   0.25   244    61.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
9    7/9/2016    Beach    134           80     126.0   0.25   229    57.25
10  7/10/2016    Beach    140           82     131.0   0.25   238    59.50
11  7/11/2016    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2016    Beach    130           84      99.0   0.25   225    56.25
13  7/13/2016    Beach    109           77      99.0   0.25   184    46.00
14  7/14/2016    Beach    122           78     113.0   0.25   207    51.75
15  7/15/2016    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2016    Beach     81           74      90.0   0.50   131    65.50
17  7/17/2016    Beach    115           77     126.0   0.50   191    95.50
18  7/18/2016     Park    131           81     122.0   0.50   223   111.50
19  7/19/2016     Park    122           78     113.0   0.50   207   103.50
20  7/20/2016     Park     71           70       NaN   0.50   113    56.50
21  7/21/2016     Park     83           77      90.0   0.50   133    66.50
22  7/22/2016     Park    112           80     108.0   0.50   187    93.50
23  7/23/2016     Park    120           81     117.0   0.50   202   101.00
24  7/24/2016     Park    121           82     117.0   0.50   203   101.50
25  7/25/2016     Park    156           84     135.0   0.50   269   134.50
26  7/26/2016     Park    176           83     158.0   0.35   305   106.75
27  7/27/2016     Park    104           80      99.0   0.35   172    60.20
28  7/28/2016     Park     96           82      90.0   0.35   159    55.65
29  7/29/2016     Park    100           81      95.0   0.35   166    58.10
30  7/30/2016    Beach     88           82      81.0   0.35   145    50.75

# 조건이 하나일 때, 일부 열만 출력
lemonade.loc[lemonade['Revenue']>45, ['Date','Revenue']]

In [33]:
lemonade.loc[lemonade['Revenue']>45, ['Date','Revenue']]

         Date  Revenue
2    7/3/2016    46.75
3    7/4/2016    58.25
4    7/5/2016    69.25
7    7/7/2016    61.00
8         NaN    52.25
9    7/9/2016    57.25
10  7/10/2016    59.50
11  7/11/2016    70.50
12  7/12/2016    56.25
13  7/13/2016    46.00
14  7/14/2016    51.75
15  7/15/2016    80.00
16  7/16/2016    65.50
17  7/17/2016    95.50
18  7/18/2016   111.50
19  7/19/2016   103.50
20  7/20/2016    56.50
21  7/21/2016    66.50
22  7/22/2016    93.50
23  7/23/2016   101.00
24  7/24/2016   101.50
25  7/25/2016   134.50
26  7/26/2016   106.75
27  7/27/2016    60.20
28  7/28/2016    55.65
29  7/29/2016    58.10
30  7/30/2016    50.75

# & (and) 조건일 때
lemonade.loc[ (lemonade['Revenue']>45) & (lemonade['Revenue']<100), ['Date', 'Revenue']]

In [34]:
lemonade.loc[ (lemonade['Revenue']>45) & (lemonade['Revenue']<100), ['Date', 'Revenue']]

         Date  Revenue
2    7/3/2016    46.75
3    7/4/2016    58.25
4    7/5/2016    69.25
7    7/7/2016    61.00
8         NaN    52.25
9    7/9/2016    57.25
10  7/10/2016    59.50
11  7/11/2016    70.50
12  7/12/2016    56.25
13  7/13/2016    46.00
14  7/14/2016    51.75
15  7/15/2016    80.00
16  7/16/2016    65.50
17  7/17/2016    95.50
20  7/20/2016    56.50
21  7/21/2016    66.50
22  7/22/2016    93.50
27  7/27/2016    60.20
28  7/28/2016    55.65
29  7/29/2016    58.10
30  7/30/2016    50.75

# | (or) 조건일 때
lemonade.loc[ (lemonade['Revenue']<45) | (lemonade['Revenue']>100), ['Date', 'Revenue']]

In [35]:
lemonade.loc[ (lemonade['Revenue']<45) | (lemonade['Revenue']>100), ['Date', 'Revenue']]

         Date  Revenue
0    7/1/2016    41.00
1    7/2/2016    41.25
5    7/6/2016    43.00
6    7/6/2016    43.00
18  7/18/2016   111.50
19  7/19/2016   103.50
23  7/23/2016   101.00
24  7/24/2016   101.50
25  7/25/2016   134.50
26  7/26/2016   106.75
31  7/31/2016    43.05

#### [정리]
- nd-darray처럼 df.loc[ ] 내에서도 AND, OR대신에 &, | 사용

In [36]:
#복사본 생성
lemonade2=lemonade.copy()
lemonade2

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0    7/1/2016     Park     97           70      90.0   0.25   164    41.00
1    7/2/2016     Park     98           72      90.0   0.25   165    41.25
2    7/3/2016     Park    110           71     104.0   0.25   187    46.75
3    7/4/2016    Beach    134           76      98.0   0.25   233    58.25
4    7/5/2016    Beach    159           78     135.0   0.25   277    69.25
5    7/6/2016    Beach    103           82      90.0   0.25   172    43.00
6    7/6/2016    Beach    103           82      90.0   0.25   172    43.00
7    7/7/2016    Beach    143           81     135.0   0.25   244    61.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
9    7/9/2016    Beach    134           80     126.0   0.25   229    57.25
10  7/10/2016    Beach    140           82     131.0   0.25   238    59.50
11  7/11/2016    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2016    Beach    130           84      99.0   0.25   225    56.25
13  7/13/2016    Beach    109           77      99.0   0.25   184    46.00
14  7/14/2016    Beach    122           78     113.0   0.25   207    51.75
15  7/15/2016    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2016    Beach     81           74      90.0   0.50   131    65.50
17  7/17/2016    Beach    115           77     126.0   0.50   191    95.50
18  7/18/2016     Park    131           81     122.0   0.50   223   111.50
19  7/19/2016     Park    122           78     113.0   0.50   207   103.50
20  7/20/2016     Park     71           70       NaN   0.50   113    56.50
21  7/21/2016     Park     83           77      90.0   0.50   133    66.50
22  7/22/2016     Park    112           80     108.0   0.50   187    93.50
23  7/23/2016     Park    120           81     117.0   0.50   202   101.00
24  7/24/2016     Park    121           82     117.0   0.50   203   101.50
25  7/25/2016     Park    156           84     135.0   0.50   269   134.50
26  7/26/2016     Park    176           83     158.0   0.35   305   106.75
27  7/27/2016     Park    104           80      99.0   0.35   172    60.20
28  7/28/2016     Park     96           82      90.0   0.35   159    55.65
29  7/29/2016     Park    100           81      95.0   0.35   166    58.10
30  7/30/2016    Beach     88           82      81.0   0.35   145    50.75
31  7/31/2016    Beach     76           82      68.0   0.35   123    43.05

In [37]:
#행위치 바꾸기
lemonade2=lemonade2.reindex([0,1,2,4,5,6,3,7,8,9])
lemonade2

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0  7/1/2016     Park     97           70      90.0   0.25   164    41.00
1  7/2/2016     Park     98           72      90.0   0.25   165    41.25
2  7/3/2016     Park    110           71     104.0   0.25   187    46.75
4  7/5/2016    Beach    159           78     135.0   0.25   277    69.25
5  7/6/2016    Beach    103           82      90.0   0.25   172    43.00
6  7/6/2016    Beach    103           82      90.0   0.25   172    43.00
3  7/4/2016    Beach    134           76      98.0   0.25   233    58.25
7  7/7/2016    Beach    143           81     135.0   0.25   244    61.00
8       NaN    Beach    123           82     113.0   0.25   209    52.25
9  7/9/2016    Beach    134           80     126.0   0.25   229    57.25

In [38]:
#열위치 바꾸기
lemonade2=lemonade2[["Location","Lemon","Date", "Temperature","Sold","Revenue",
           "Leaflets","Price"]]
lemonade2

  Location  Lemon      Date  Temperature  Sold  Revenue  Leaflets  Price
0     Park     97  7/1/2016           70   164    41.00      90.0   0.25
1     Park     98  7/2/2016           72   165    41.25      90.0   0.25
2     Park    110  7/3/2016           71   187    46.75     104.0   0.25
4    Beach    159  7/5/2016           78   277    69.25     135.0   0.25
5    Beach    103  7/6/2016           82   172    43.00      90.0   0.25
6    Beach    103  7/6/2016           82   172    43.00      90.0   0.25
3    Beach    134  7/4/2016           76   233    58.25      98.0   0.25
7    Beach    143  7/7/2016           81   244    61.00     135.0   0.25
8    Beach    123       NaN           82   209    52.25     113.0   0.25
9    Beach    134  7/9/2016           80   229    57.25     126.0   0.25