# Pandas (cont.)

# 1. 행 추가

In [32]:
import pandas as pd

In [33]:
lemonade=pd.read_csv("lemonade2.csv")

lemonade2=lemonade[0:2]
lemonade2

In [34]:
lemonade2=lemonade[0:2]
lemonade2

       Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0  7/1/2024     Park     97           70      90.0   0.25   164    41.00
1  7/2/2024     Park     98           72      90.0   0.25   165    41.25

lemonade3=pd.concat([lemonade, lemonade2])
lemonade3

In [35]:
lemonade3=pd.concat([lemonade, lemonade2])
lemonade3

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25

#총 34개행, 0~33 (추가된 2개 포함)
lemonade3[0:34]

In [36]:
lemonade3[0:34]

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25

In [37]:
# 상기와 동일한 결과를 얻기 위해서 <blank>들어갈 것은 loc인가 iloc인가?
# 왜 0:33 이 아니고 0:34인가?
lemonade3.iloc[0:33]

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00

# 2. 데이터 전처리 - 정렬, 그룹핑, 결측값, 중복값 처리

## 1) sort_values() - 데이터 정렬

lemonade.sort_values(by=['Temperature'])

In [38]:
lemonade.sort_values(by=['Temperature'])

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
8         NaN    Beach    123           82     113.0   0.25   209    52.25
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50

* **inplace = True  --> 정렬한 값이 lemonade에 바로 저장**
* **inplace = True 없이 실행한 경우 1회성으로 결과만 보여줄뿐 lemonade의 실제 내용은 바뀌지 않음**

In [39]:
lemonade

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05

lemonade.sort_values(by=['Temperature'], inplace = True)

In [40]:
lemonade.sort_values(by=['Temperature'], inplace = True)

In [41]:
lemonade

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
8         NaN    Beach    123           82     113.0   0.25   209    52.25
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50

- 내림차순으로 하고 싶다면? ascending= False

lemonade.sort_values(by=['Temperature'], ascending= False, inplace = True)

In [42]:
lemonade.sort_values(by=['Temperature'], ascending= False, inplace = True)

In [43]:
lemonade

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00

### 만약 Temperature로 정렬 후 다시 Revenue로 정렬하고 싶다면? 다음 코드를 어떻게 수정해야 할까?

In [44]:
lemonade.sort_values(by=['Temperature'], ascending= False)

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00

### 만약 Temperature로는 내림차순 정렬, 다시 Revenue로는 오름차순 정렬을 하고 싶다면?

lemonade.sort_values(by=['Temperature', 'Revenue'], ascending=[False, True])

In [45]:
lemonade.sort_values(by=['Temperature', 'Revenue'], ascending=[False, True])

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
8         NaN    Beach    123           82     113.0   0.25   209    52.25
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50

## 2) groupby() - 데이터 그룹핑
- groupby(by=그룹핑 기준컬럼).통계함수() 형태로 그룹별 통계량 확인

lemonade.groupby(by=['Location'])

In [46]:
lemonade.groupby(by=['Location'])

lemonade.groupby(by=['Location']).count()

In [47]:
lemonade.groupby(by=['Location']).count()

          Date  Lemon  Temperature  Leaflets  Price  Sold  Revenue
Location
Beach       16     17           17        17     17    17       17
Park        15     15           15        14     15    15       15

lemonade.groupby(by=['Location']).mean()

In [48]:
lemonade.groupby(by=['Location']).mean(numeric_only=True)

               Lemon  Temperature    Leaflets     Price        Sold    Revenue
Location
Beach     118.823529    79.705882  108.058824  0.305882  201.294118  58.988235
Park      113.133333    78.133333  109.142857  0.410000  190.333333  78.546667

- location별 그룹핑 하여 특정열(Revenue)만의 통계량을 보고싶다면?
    - groupby(by=그룹핑 기준컬럼)['열이름'].통계함수()

lemonade.groupby(by=['Location'])['Revenue'].max()

In [49]:
lemonade.groupby(by=['Location'])['Revenue'].max()

Location
Beach     95.5
Park     134.5
Name: Revenue, dtype: float64

lemonade.groupby(by=['Location'])['Revenue'].min()

In [50]:
lemonade.groupby(by=['Location'])['Revenue'].min()

Location
Beach    43.0
Park     41.0
Name: Revenue, dtype: float64

## 3) 결측 데이터 처리하기
### isna(), isnull() -  결측데이터 여부 확인

In [51]:
lemonade.isna().tail(20)

     Date  Location  Lemon  Temperature  Leaflets  Price   Sold  Revenue
7   False     False  False        False     False  False  False    False
23  False     False  False        False     False  False  False    False
29  False     False  False        False     False  False  False    False
18  False     False  False        False     False  False  False    False
22  False     False  False        False     False  False  False    False
27  False     False  False        False     False  False  False    False
9   False     False  False        False     False  False  False    False
19  False     False  False        False     False  False  False    False
4   False     False  False        False     False  False  False    False
14  False     False  False        False     False  False  False    False
21  False     False  False        False     False  False  False    False
17  False     False  False        False     False  False  False    False
13  False     False  False        False     False  False  False    False
3   False     False  False        False     False  False  False    False
15  False     False  False        False     False  False  False    False
16  False     False  False        False     False  False  False    False
1   False     False  False        False     False  False  False    False
2   False     False  False        False     False  False  False    False
20  False     False  False        False      True  False  False    False
0   False     False  False        False     False  False  False    False

- Leaflets (index 20)에 결손 존재

In [52]:
lemonade.isna( ).head(10)

     Date  Location  Lemon  Temperature  Leaflets  Price   Sold  Revenue
25  False     False  False        False     False  False  False    False
12  False     False  False        False     False  False  False    False
11  False     False  False        False     False  False  False    False
26  False     False  False        False     False  False  False    False
31  False     False  False        False     False  False  False    False
5   False     False  False        False     False  False  False    False
8    True     False  False        False     False  False  False    False
10  False     False  False        False     False  False  False    False
30  False     False  False        False     False  False  False    False
6   False     False  False        False     False  False  False    False

- Date (index 8)에 결손 존재

lemonade.isna( ).sum( )

In [53]:
lemonade.isna( ).sum( )

Date           1
Location       0
Lemon          0
Temperature    0
Leaflets       1
Price          0
Sold           0
Revenue        0
dtype: int64

lemonade.isnull( )  #동일한 결과

In [54]:
lemonade.isnull( )

     Date  Location  Lemon  Temperature  Leaflets  Price   Sold  Revenue
25  False     False  False        False     False  False  False    False
12  False     False  False        False     False  False  False    False
11  False     False  False        False     False  False  False    False
26  False     False  False        False     False  False  False    False
31  False     False  False        False     False  False  False    False
5   False     False  False        False     False  False  False    False
8    True     False  False        False     False  False  False    False
10  False     False  False        False     False  False  False    False
30  False     False  False        False     False  False  False    False
6   False     False  False        False     False  False  False    False
24  False     False  False        False     False  False  False    False
28  False     False  False        False     False  False  False    False
7   False     False  False        False     False  False  False    False
23  False     False  False        False     False  False  False    False
29  False     False  False        False     False  False  False    False
18  False     False  False        False     False  False  False    False
22  False     False  False        False     False  False  False    False
27  False     False  False        False     False  False  False    False
9   False     False  False        False     False  False  False    False
19  False     False  False        False     False  False  False    False
4   False     False  False        False     False  False  False    False
14  False     False  False        False     False  False  False    False
21  False     False  False        False     False  False  False    False
17  False     False  False        False     False  False  False    False
13  False     False  False        False     False  False  False    False
3   False     False  False        False     False  False  False    False
15  False     False  False        False     False  False  False    False
16  False     False  False        False     False  False  False    False
1   False     False  False        False     False  False  False    False
2   False     False  False        False     False  False  False    False
20  False     False  False        False      True  False  False    False
0   False     False  False        False     False  False  False    False

lemonade.isnull( ).sum()

In [55]:
lemonade.isnull( ).sum()

Date           1
Location       0
Lemon          0
Temperature    0
Leaflets       1
Price          0
Sold           0
Revenue        0
dtype: int64

### fillna( ) - Missing 데이터 대체하기

In [56]:
lemonade.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 25 to 0
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         31 non-null     object
 1   Location     32 non-null     object
 2   Lemon        32 non-null     int64
 3   Temperature  32 non-null     int64
 4   Leaflets     31 non-null     float64
 5   Price        32 non-null     float64
 6   Sold         32 non-null     int64
 7   Revenue      32 non-null     float64
dtypes: float64(3), int64(3), object(2)
memory usage: 2.2+ KB

In [57]:
# 주의! 아래처럼하면 어떻게 될까?
lemonade['Date'].fillna('9/9/9999')

25    7/25/2024
12    7/12/2024
11    7/11/2024
26    7/26/2024
31    7/31/2024
5      7/6/2024
8      9/9/9999
10    7/10/2024
30    7/30/2024
6      7/6/2024
24    7/24/2024
28    7/28/2024
7      7/7/2024
23    7/23/2024
29    7/29/2024
18    7/18/2024
22    7/22/2024
27    7/27/2024
9      7/9/2024
19    7/19/2024
4      7/5/2024
14    7/14/2024
21    7/21/2024
17    7/17/2024
13    7/13/2024
3      7/4/2024
15    7/15/2024
16    7/16/2024
1      7/2/2024
2      7/3/2024
20    7/20/2024
0      7/1/2024
Name: Date, dtype: object

In [58]:
lemonade  #다시 확인해 보면 Leaflets에 결측값이 그대로 남아 있음

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
25  7/25/2024     Park    156           84     135.0   0.50   269   134.50
12  7/12/2024    Beach    130           84      99.0   0.25   225    56.25
11  7/11/2024    Beach    162           83     135.0   0.25   282    70.50
26  7/26/2024     Park    176           83     158.0   0.35   305   106.75
31  7/31/2024    Beach     76           82      68.0   0.35   123    43.05
5    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
8         NaN    Beach    123           82     113.0   0.25   209    52.25
10  7/10/2024    Beach    140           82     131.0   0.25   238    59.50
30  7/30/2024    Beach     88           82      81.0   0.35   145    50.75
6    7/6/2024    Beach    103           82      90.0   0.25   172    43.00
24  7/24/2024     Park    121           82     117.0   0.50   203   101.50
28  7/28/2024     Park     96           82      90.0   0.35   159    55.65
7    7/7/2024    Beach    143           81     135.0   0.25   244    61.00
23  7/23/2024     Park    120           81     117.0   0.50   202   101.00
29  7/29/2024     Park    100           81      95.0   0.35   166    58.10
18  7/18/2024     Park    131           81     122.0   0.50   223   111.50
22  7/22/2024     Park    112           80     108.0   0.50   187    93.50
27  7/27/2024     Park    104           80      99.0   0.35   172    60.20
9    7/9/2024    Beach    134           80     126.0   0.25   229    57.25
19  7/19/2024     Park    122           78     113.0   0.50   207   103.50
4    7/5/2024    Beach    159           78     135.0   0.25   277    69.25
14  7/14/2024    Beach    122           78     113.0   0.25   207    51.75
21  7/21/2024     Park     83           77      90.0   0.50   133    66.50
17  7/17/2024    Beach    115           77     126.0   0.50   191    95.50
13  7/13/2024    Beach    109           77      99.0   0.25   184    46.00
3    7/4/2024    Beach    134           76      98.0   0.25   233    58.25
15  7/15/2024    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2024    Beach     81           74      90.0   0.50   131    65.50
1    7/2/2024     Park     98           72      90.0   0.25   165    41.25
2    7/3/2024     Park    110           71     104.0   0.25   187    46.75
20  7/20/2024     Park     71           70       NaN   0.50   113    56.50
0    7/1/2024     Park     97           70      90.0   0.25   164    41.00

lemonade['Date'] = lemonade['Date'].fillna(0)

In [26]:
lemonade['Date'] = lemonade['Date'].fillna(0)

In [27]:
lemonade  
#date결측값은 0으로 치환
#Leaflets결측값은 남아있음

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
25  7/25/2016     Park    156           84     135.0   0.50   269   134.50
12  7/12/2016    Beach    130           84      99.0   0.25   225    56.25
11  7/11/2016    Beach    162           83     135.0   0.25   282    70.50
26  7/26/2016     Park    176           83     158.0   0.35   305   106.75
31  7/31/2016    Beach     76           82      68.0   0.35   123    43.05
5    7/6/2016    Beach    103           82      90.0   0.25   172    43.00
8           0    Beach    123           82     113.0   0.25   209    52.25
10  7/10/2016    Beach    140           82     131.0   0.25   238    59.50
30  7/30/2016    Beach     88           82      81.0   0.35   145    50.75
6    7/6/2016    Beach    103           82      90.0   0.25   172    43.00
24  7/24/2016     Park    121           82     117.0   0.50   203   101.50
28  7/28/2016     Park     96           82      90.0   0.35   159    55.65
7    7/7/2016    Beach    143           81     135.0   0.25   244    61.00
23  7/23/2016     Park    120           81     117.0   0.50   202   101.00
29  7/29/2016     Park    100           81      95.0   0.35   166    58.10
18  7/18/2016     Park    131           81     122.0   0.50   223   111.50
22  7/22/2016     Park    112           80     108.0   0.50   187    93.50
27  7/27/2016     Park    104           80      99.0   0.35   172    60.20
9    7/9/2016    Beach    134           80     126.0   0.25   229    57.25
19  7/19/2016     Park    122           78     113.0   0.50   207   103.50
4    7/5/2016    Beach    159           78     135.0   0.25   277    69.25
14  7/14/2016    Beach    122           78     113.0   0.25   207    51.75
21  7/21/2016     Park     83           77      90.0   0.50   133    66.50
17  7/17/2016    Beach    115           77     126.0   0.50   191    95.50
13  7/13/2016    Beach    109           77      99.0   0.25   184    46.00
3    7/4/2016    Beach    134           76      98.0   0.25   233    58.25
15  7/15/2016    Beach     98           75     108.0   0.50   160    80.00
16  7/16/2016    Beach     81           74      90.0   0.50   131    65.50
1    7/2/2016     Park     98           72      90.0   0.25   165    41.25
2    7/3/2016     Park    110           71     104.0   0.25   187    46.75
20  7/20/2016     Park     71           70       NaN   0.50   113    56.50
0    7/1/2016     Park     97           70      90.0   0.25   164    41.00

# Leafleats결측값을 평균값으로 치환

lemonade['Leaflets'] = lemonade['Leaflets'].fillna(lemonade['Leaflets'].mean())
lemonade

In [28]:
lemonade['Leaflets'] = lemonade['Leaflets'].fillna(lemonade['Leaflets'].mean())
lemonade

         Date Location  Lemon  Temperature    Leaflets  Price  Sold  Revenue
25  7/25/2016     Park    156           84  135.000000   0.50   269   134.50
12  7/12/2016    Beach    130           84   99.000000   0.25   225    56.25
11  7/11/2016    Beach    162           83  135.000000   0.25   282    70.50
26  7/26/2016     Park    176           83  158.000000   0.35   305   106.75
31  7/31/2016    Beach     76           82   68.000000   0.35   123    43.05
5    7/6/2016    Beach    103           82   90.000000   0.25   172    43.00
8           0    Beach    123           82  113.000000   0.25   209    52.25
10  7/10/2016    Beach    140           82  131.000000   0.25   238    59.50
30  7/30/2016    Beach     88           82   81.000000   0.35   145    50.75
6    7/6/2016    Beach    103           82   90.000000   0.25   172    43.00
24  7/24/2016     Park    121           82  117.000000   0.50   203   101.50
28  7/28/2016     Park     96           82   90.000000   0.35   159    55.65
7    7/7/2016    Beach    143           81  135.000000   0.25   244    61.00
23  7/23/2016     Park    120           81  117.000000   0.50   202   101.00
29  7/29/2016     Park    100           81   95.000000   0.35   166    58.10
18  7/18/2016     Park    131           81  122.000000   0.50   223   111.50
22  7/22/2016     Park    112           80  108.000000   0.50   187    93.50
27  7/27/2016     Park    104           80   99.000000   0.35   172    60.20
9    7/9/2016    Beach    134           80  126.000000   0.25   229    57.25
19  7/19/2016     Park    122           78  113.000000   0.50   207   103.50
4    7/5/2016    Beach    159           78  135.000000   0.25   277    69.25
14  7/14/2016    Beach    122           78  113.000000   0.25   207    51.75
21  7/21/2016     Park     83           77   90.000000   0.50   133    66.50
17  7/17/2016    Beach    115           77  126.000000   0.50   191    95.50
13  7/13/2016    Beach    109           77   99.000000   0.25   184    46.00
3    7/4/2016    Beach    134           76   98.000000   0.25   233    58.25
15  7/15/2016    Beach     98           75  108.000000   0.50   160    80.00
16  7/16/2016    Beach     81           74   90.000000   0.50   131    65.50
1    7/2/2016     Park     98           72   90.000000   0.25   165    41.25
2    7/3/2016     Park    110           71  104.000000   0.25   187    46.75
20  7/20/2016     Park     71           70  108.548387   0.50   113    56.50
0    7/1/2016     Park     97           70   90.000000   0.25   164    41.00

## 4) 중복 데이터 제거하기
### duplicated() - 중복 여부 확인 
- 행단위로 체크

lemonade.duplicated()

In [29]:
lemonade.duplicated()

25    False
12    False
11    False
26    False
31    False
5     False
8     False
10    False
30    False
6      True
24    False
28    False
7     False
23    False
29    False
18    False
22    False
27    False
9     False
19    False
4     False
14    False
21    False
17    False
13    False
3     False
15    False
16    False
1     False
2     False
20    False
0     False
dtype: bool

In [30]:
lemonade.head(10)  #7월6일 데이터가 2건

         Date Location  Lemon  Temperature  Leaflets  Price  Sold  Revenue
25  7/25/2016     Park    156           84     135.0   0.50   269   134.50
12  7/12/2016    Beach    130           84      99.0   0.25   225    56.25
11  7/11/2016    Beach    162           83     135.0   0.25   282    70.50
26  7/26/2016     Park    176           83     158.0   0.35   305   106.75
31  7/31/2016    Beach     76           82      68.0   0.35   123    43.05
5    7/6/2016    Beach    103           82      90.0   0.25   172    43.00
8           0    Beach    123           82     113.0   0.25   209    52.25
10  7/10/2016    Beach    140           82     131.0   0.25   238    59.50
30  7/30/2016    Beach     88           82      81.0   0.35   145    50.75
6    7/6/2016    Beach    103           82      90.0   0.25   172    43.00

In [31]:
lemonade.duplicated().sum()

1

- Parameters
    - keep
        - ‘first’ : Drop duplicates except for the first occurrence. (default)
        - ‘last’ : Drop duplicates except for the last occurrence.
        -  False : Drop all duplicates.
     -  ignore_index
        - True : 원래 index유지안하고 새로 indexing
        - False: 원래 index유지 (default)

In [32]:
#중복값 제거  
lemonade.drop_duplicates(ignore_index=True) #원래 index유지안하고 새로 indexing

         Date Location  Lemon  Temperature    Leaflets  Price  Sold  Revenue
0   7/25/2016     Park    156           84  135.000000   0.50   269   134.50
1   7/12/2016    Beach    130           84   99.000000   0.25   225    56.25
2   7/11/2016    Beach    162           83  135.000000   0.25   282    70.50
3   7/26/2016     Park    176           83  158.000000   0.35   305   106.75
4   7/31/2016    Beach     76           82   68.000000   0.35   123    43.05
5    7/6/2016    Beach    103           82   90.000000   0.25   172    43.00
6           0    Beach    123           82  113.000000   0.25   209    52.25
7   7/10/2016    Beach    140           82  131.000000   0.25   238    59.50
8   7/30/2016    Beach     88           82   81.000000   0.35   145    50.75
9   7/24/2016     Park    121           82  117.000000   0.50   203   101.50
10  7/28/2016     Park     96           82   90.000000   0.35   159    55.65
11   7/7/2016    Beach    143           81  135.000000   0.25   244    61.00
12  7/23/2016     Park    120           81  117.000000   0.50   202   101.00
13  7/29/2016     Park    100           81   95.000000   0.35   166    58.10
14  7/18/2016     Park    131           81  122.000000   0.50   223   111.50
15  7/22/2016     Park    112           80  108.000000   0.50   187    93.50
16  7/27/2016     Park    104           80   99.000000   0.35   172    60.20
17   7/9/2016    Beach    134           80  126.000000   0.25   229    57.25
18  7/19/2016     Park    122           78  113.000000   0.50   207   103.50
19   7/5/2016    Beach    159           78  135.000000   0.25   277    69.25
20  7/14/2016    Beach    122           78  113.000000   0.25   207    51.75
21  7/21/2016     Park     83           77   90.000000   0.50   133    66.50
22  7/17/2016    Beach    115           77  126.000000   0.50   191    95.50
23  7/13/2016    Beach    109           77   99.000000   0.25   184    46.00
24   7/4/2016    Beach    134           76   98.000000   0.25   233    58.25
25  7/15/2016    Beach     98           75  108.000000   0.50   160    80.00
26  7/16/2016    Beach     81           74   90.000000   0.50   131    65.50
27   7/2/2016     Park     98           72   90.000000   0.25   165    41.25
28   7/3/2016     Park    110           71  104.000000   0.25   187    46.75
29  7/20/2016     Park     71           70  108.548387   0.50   113    56.50
30   7/1/2016     Park     97           70   90.000000   0.25   164    41.00

In [33]:
#원본에는 반영되지 않음
lemonade

         Date Location  Lemon  Temperature    Leaflets  Price  Sold  Revenue
25  7/25/2016     Park    156           84  135.000000   0.50   269   134.50
12  7/12/2016    Beach    130           84   99.000000   0.25   225    56.25
11  7/11/2016    Beach    162           83  135.000000   0.25   282    70.50
26  7/26/2016     Park    176           83  158.000000   0.35   305   106.75
31  7/31/2016    Beach     76           82   68.000000   0.35   123    43.05
5    7/6/2016    Beach    103           82   90.000000   0.25   172    43.00
8           0    Beach    123           82  113.000000   0.25   209    52.25
10  7/10/2016    Beach    140           82  131.000000   0.25   238    59.50
30  7/30/2016    Beach     88           82   81.000000   0.35   145    50.75
6    7/6/2016    Beach    103           82   90.000000   0.25   172    43.00
24  7/24/2016     Park    121           82  117.000000   0.50   203   101.50
28  7/28/2016     Park     96           82   90.000000   0.35   159    55.65
7    7/7/2016    Beach    143           81  135.000000   0.25   244    61.00
23  7/23/2016     Park    120           81  117.000000   0.50   202   101.00
29  7/29/2016     Park    100           81   95.000000   0.35   166    58.10
18  7/18/2016     Park    131           81  122.000000   0.50   223   111.50
22  7/22/2016     Park    112           80  108.000000   0.50   187    93.50
27  7/27/2016     Park    104           80   99.000000   0.35   172    60.20
9    7/9/2016    Beach    134           80  126.000000   0.25   229    57.25
19  7/19/2016     Park    122           78  113.000000   0.50   207   103.50
4    7/5/2016    Beach    159           78  135.000000   0.25   277    69.25
14  7/14/2016    Beach    122           78  113.000000   0.25   207    51.75
21  7/21/2016     Park     83           77   90.000000   0.50   133    66.50
17  7/17/2016    Beach    115           77  126.000000   0.50   191    95.50
13  7/13/2016    Beach    109           77   99.000000   0.25   184    46.00
3    7/4/2016    Beach    134           76   98.000000   0.25   233    58.25
15  7/15/2016    Beach     98           75  108.000000   0.50   160    80.00
16  7/16/2016    Beach     81           74   90.000000   0.50   131    65.50
1    7/2/2016     Park     98           72   90.000000   0.25   165    41.25
2    7/3/2016     Park    110           71  104.000000   0.25   187    46.75
20  7/20/2016     Park     71           70  108.548387   0.50   113    56.50
0    7/1/2016     Park     97           70   90.000000   0.25   164    41.00

In [34]:
lemonade.drop_duplicates(ignore_index=False)   #원래 index유지

         Date Location  Lemon  Temperature    Leaflets  Price  Sold  Revenue
25  7/25/2016     Park    156           84  135.000000   0.50   269   134.50
12  7/12/2016    Beach    130           84   99.000000   0.25   225    56.25
11  7/11/2016    Beach    162           83  135.000000   0.25   282    70.50
26  7/26/2016     Park    176           83  158.000000   0.35   305   106.75
31  7/31/2016    Beach     76           82   68.000000   0.35   123    43.05
5    7/6/2016    Beach    103           82   90.000000   0.25   172    43.00
8           0    Beach    123           82  113.000000   0.25   209    52.25
10  7/10/2016    Beach    140           82  131.000000   0.25   238    59.50
30  7/30/2016    Beach     88           82   81.000000   0.35   145    50.75
24  7/24/2016     Park    121           82  117.000000   0.50   203   101.50
28  7/28/2016     Park     96           82   90.000000   0.35   159    55.65
7    7/7/2016    Beach    143           81  135.000000   0.25   244    61.00
23  7/23/2016     Park    120           81  117.000000   0.50   202   101.00
29  7/29/2016     Park    100           81   95.000000   0.35   166    58.10
18  7/18/2016     Park    131           81  122.000000   0.50   223   111.50
22  7/22/2016     Park    112           80  108.000000   0.50   187    93.50
27  7/27/2016     Park    104           80   99.000000   0.35   172    60.20
9    7/9/2016    Beach    134           80  126.000000   0.25   229    57.25
19  7/19/2016     Park    122           78  113.000000   0.50   207   103.50
4    7/5/2016    Beach    159           78  135.000000   0.25   277    69.25
14  7/14/2016    Beach    122           78  113.000000   0.25   207    51.75
21  7/21/2016     Park     83           77   90.000000   0.50   133    66.50
17  7/17/2016    Beach    115           77  126.000000   0.50   191    95.50
13  7/13/2016    Beach    109           77   99.000000   0.25   184    46.00
3    7/4/2016    Beach    134           76   98.000000   0.25   233    58.25
15  7/15/2016    Beach     98           75  108.000000   0.50   160    80.00
16  7/16/2016    Beach     81           74   90.000000   0.50   131    65.50
1    7/2/2016     Park     98           72   90.000000   0.25   165    41.25
2    7/3/2016     Park    110           71  104.000000   0.25   187    46.75
20  7/20/2016     Park     71           70  108.548387   0.50   113    56.50
0    7/1/2016     Park     97           70   90.000000   0.25   164    41.00

In [35]:
#새로 indexing
#원본에 반영: inplace=??

lemonade.drop_duplicates(keep='first', inplace=True, ignore_index=True)

In [36]:
lemonade

         Date Location  Lemon  Temperature    Leaflets  Price  Sold  Revenue
0   7/25/2016     Park    156           84  135.000000   0.50   269   134.50
1   7/12/2016    Beach    130           84   99.000000   0.25   225    56.25
2   7/11/2016    Beach    162           83  135.000000   0.25   282    70.50
3   7/26/2016     Park    176           83  158.000000   0.35   305   106.75
4   7/31/2016    Beach     76           82   68.000000   0.35   123    43.05
5    7/6/2016    Beach    103           82   90.000000   0.25   172    43.00
6           0    Beach    123           82  113.000000   0.25   209    52.25
7   7/10/2016    Beach    140           82  131.000000   0.25   238    59.50
8   7/30/2016    Beach     88           82   81.000000   0.35   145    50.75
9   7/24/2016     Park    121           82  117.000000   0.50   203   101.50
10  7/28/2016     Park     96           82   90.000000   0.35   159    55.65
11   7/7/2016    Beach    143           81  135.000000   0.25   244    61.00
12  7/23/2016     Park    120           81  117.000000   0.50   202   101.00
13  7/29/2016     Park    100           81   95.000000   0.35   166    58.10
14  7/18/2016     Park    131           81  122.000000   0.50   223   111.50
15  7/22/2016     Park    112           80  108.000000   0.50   187    93.50
16  7/27/2016     Park    104           80   99.000000   0.35   172    60.20
17   7/9/2016    Beach    134           80  126.000000   0.25   229    57.25
18  7/19/2016     Park    122           78  113.000000   0.50   207   103.50
19   7/5/2016    Beach    159           78  135.000000   0.25   277    69.25
20  7/14/2016    Beach    122           78  113.000000   0.25   207    51.75
21  7/21/2016     Park     83           77   90.000000   0.50   133    66.50
22  7/17/2016    Beach    115           77  126.000000   0.50   191    95.50
23  7/13/2016    Beach    109           77   99.000000   0.25   184    46.00
24   7/4/2016    Beach    134           76   98.000000   0.25   233    58.25
25  7/15/2016    Beach     98           75  108.000000   0.50   160    80.00
26  7/16/2016    Beach     81           74   90.000000   0.50   131    65.50
27   7/2/2016     Park     98           72   90.000000   0.25   165    41.25
28   7/3/2016     Park    110           71  104.000000   0.25   187    46.75
29  7/20/2016     Park     71           70  108.548387   0.50   113    56.50
30   7/1/2016     Park     97           70   90.000000   0.25   164    41.00

In [37]:
lemonade.duplicated().sum()

0